### ISSUE TITLE
No se almacenan los binarios compilados en el repositorio

### ISSUE THREAD

**Issue by evolentini** [gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3#1]
En el repositorio solo debe almacenar código fuente, la carpeta `build` debe agregarse en el archivo `.gitignore` y eliminarse de repositorio

**Comment by gonvila84** [comment]
Resuelto - Se elimino la carpeta /leds/build del repositorio y se configuro .gitignore para ignorarla en los siguientes push.
