### ISSUE TITLE
Se deben eliminar las constantes mágicas del código de producción

### ISSUE THREAD

**Issue by evolentini** [gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3#2]
https://github.com/gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3/blob/8dd3917ae0093072355c51247512095681120b5b/leds/src/leds.c#L15

https://github.com/gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3/blob/8dd3917ae0093072355c51247512095681120b5b/leds/src/leds.c#L19

https://github.com/gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3/blob/8dd3917ae0093072355c51247512095681120b5b/leds/src/leds.c#L24

https://github.com/gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3/blob/8dd3917ae0093072355c51247512095681120b5b/leds/src/leds.c#L28

**Comment by gonvila84** [comment]
Resuelto - Se eliminaros las constantes y se reemplazaron por valores definidos mediante defines
