### ISSUE TITLE
Todas las funciones de la biblioteca deben tener un comportamiento uniforme

### ISSUE THREAD

**Issue by evolentini** [gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3#3]
Si la función `LedQueryState()` controla los límites del parámetro, entonces todas las otras funciones de la biblioteca deberían hacer lo mismo. Ademas el código que controla los limites no debería estar repetido sino y centralizando el control en una función (o macro) interna.

**Comment by gonvila84** [comment]
Se agrega la verificación de límites para los valores de led y se generaliza en una función
