### ISSUE TITLE
Se debe refactorizar el código de producción para eliminar repeticiones

### ISSUE THREAD

**Issue by evolentini** [gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3#4]
En esta línea se debería llamar a la función `LedTurnOffAllAtOnce()` en lugar de repetir la asignación de valores a la variable.

https://github.com/gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3/blob/8dd3917ae0093072355c51247512095681120b5b/leds/src/leds.c#L24

**Comment by gonvila84** [comment]
Resuelto - Se reemplaza la asignación directa por el uso de una función
