### ISSUE TITLE
Se puede implementar de otra forma

### ISSUE THREAD

**Issue by evolentini** [gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3#5]
Dado que ya esta asegurado que todos los les inician apagados estas pruebas

https://github.com/gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3/blob/8dd3917ae0093072355c51247512095681120b5b/leds/test/test_leds.c#L53-L65

se podrían implementar tambien como

```c
//Se pueden prender todos los LEDs de una vez.
void test_TurnOnAllLeds(void){
    LedTurnOnAllAtOnce();
    TEST_ASSERT_EQUAL_HEX16(0xFFFF, ledsVirtuales);
}

//Se pueden apagar todos los LEDs de una vez.
void test_TurnOffAllLeds(void){
    LedTurnOnAllAtOnce();
    LedTurnOffAllAtOnce();
    TEST_ASSERT_EQUAL_HEX16(0x0, ledsVirtuales);
}
```

lo que personalmente me resulta más prolijo. De todas formas lo que hiciste no está mal y no hace falta que lo cambies.

**Comment by gonvila84** [comment]
Resuelto - Aunque fuese opcional, se toma la sugerencia y se modifica el código.
