### ISSUE TITLE
Se debe refactorizar el código como para enviarlo a un repositorio

### ISSUE THREAD

**Issue by evolentini** [gonvila84/FIUBA_CESE_TESTINGSOFTWARE_TP3#6]
La idea es que el código de producción y de las pruebas quede exactamente igual que si lo enviaran a revisión para usarlo en un proyecto real. La parte que vos escribiste esta muy prolija, pero la parte que se copio de clase debería ser mejorara para que quede como un código uniforme.

**Comment by gonvila84** [comment]
Se mejoró el código para darle mayor coherencia.

1. Se agregaron comentarios en un formato uniforme
2. Se modifico el espaciado y estilo en las funciones para darle coherencia al estilo del código
3. Se eliminaron todas las constantes mágicas
